import React from 'react';
import type { ClinicalNote, NoteMeta } from '../types/patient';

const VITAL_LABELS: Record<string, string> = {
  blood_pressure: 'Blood pressure',
  heart_rate: 'Heart rate',
  temperature: 'Temperature',
  oxygen_saturation: 'O₂ saturation',
  respiratory_rate: 'Respiratory rate',
  weight: 'Weight',
  height: 'Height',
};

const label = (key: string) => VITAL_LABELS[key] ?? key.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());

const asText = (v: unknown): string => (Array.isArray(v) ? v.map(asText).join(', ') : typeof v === 'object' && v ? JSON.stringify(v) : String(v ?? ''));

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div>
    <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-1">{title}</h4>
    {children}
  </div>
);

const Fields: React.FC<{ data?: Record<string, unknown> }> = ({ data }) => {
  const entries = Object.entries(data ?? {});
  if (!entries.length) return null;
  return (
    <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1 text-sm">
      {entries.map(([k, v]) => (
        <div key={k} className="flex gap-2">
          <dt className="text-gray-500 shrink-0">{label(k)}:</dt>
          <dd className="text-gray-900">{asText(v)}</dd>
        </div>
      ))}
    </dl>
  );
};

const List: React.FC<{ items?: unknown }> = ({ items }) =>
  Array.isArray(items) && items.length ? (
    <ul className="list-disc pl-5 text-sm text-gray-900 space-y-0.5">
      {items.map((it, i) => (
        <li key={i}>{asText(it)}</li>
      ))}
    </ul>
  ) : null;

const NoteView: React.FC<{ note: ClinicalNote; meta?: NoteMeta }> = ({ note, meta }) => {
  const hasAny =
    note.summary || note.vitals || note.symptoms || note.medical_history || note.patient_concerns ||
    note.nurse_observations || note.additional_characteristics;
  return (
    <div className="space-y-3">
      {note.summary && (
        <Section title="Summary">
          <p className="text-sm text-gray-900">{note.summary}</p>
        </Section>
      )}
      {note.vitals && (
        <Section title="Vitals">
          <Fields data={note.vitals} />
        </Section>
      )}
      {note.symptoms && (
        <Section title="Symptoms">
          <Fields data={note.symptoms} />
        </Section>
      )}
      {note.medical_history && (
        <Section title="Medical history mentioned">
          <Fields data={note.medical_history} />
        </Section>
      )}
      {note.patient_concerns && (
        <Section title="Patient concerns">
          <List items={note.patient_concerns} />
        </Section>
      )}
      {note.nurse_observations && (
        <Section title="Clinician observations">
          <List items={note.nurse_observations} />
        </Section>
      )}
      {note.additional_characteristics && (
        <Section title="Other">
          <Fields data={note.additional_characteristics} />
        </Section>
      )}
      {!hasAny && <p className="text-sm text-gray-500">The model found nothing to extract from this transcript.</p>}
      {meta && (
        <p className="text-xs text-gray-400">
          Generated by {meta.provider} ({meta.model}) on {new Date(meta.generatedAt).toLocaleString()}. Review before use.
        </p>
      )}
    </div>
  );
};

export default NoteView;
